Add IntelliJ plugin to the supported editors list
veelenga/awesome-crystal pull request #608
Opened 2023-03-23 19:17 UTC by asedunov

## Link
https://github.com/asedunov/intellij-crystal-lang

## Checklist
* [ ] - Shard is at least 30 days old.
* [ ] - Shard has CI implemented.
* [ ] - Shard has daily/weekly periodic builds (ideally with Crystal latest and nightly).

2023-03-23 19:39 UTC, Blacksmoke16 approved these changes

2023-03-23 19:42 UTC, Blacksmoke16 requested changes
This should fix CI

2023-03-23 19:42 UTC, Blacksmoke16 commented on README.md
> +   * [intellij-crystal-lang](https://github.com/asedunov/intellij-crystal-lang) - Crystal support for the JetBrains IDEs
```suggestion
   * [intellij-crystal-lang](https://github.com/asedunov/intellij-crystal-lang) - Crystal support for the JetBrains IDEs
```

2023-03-23 20:32 UTC, Blacksmoke16 approved these changes

2023-03-24 08:03 UTC, veelenga approved these changes

2023-03-24 08:03 UTC, merged